---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check if system relies on auth select tool
  ansible.builtin.stat:
    path: /usr/bin/authselect
  register: result_authselect_present
  when: '"pam" in ansible_facts.packages'

- name: Collect the Available authselect Features
  ansible.builtin.command:
    cmd: authselect list-features sssd
  register: result_authselect_available_features
  changed_when: false
  check_mode: false
  when:
    - '"pam" in ansible_facts.packages'
    - result_authselect_present.stat.exists

- name: Configure pam_lastlog.so Using authselect Feature
  when:
    - result_auithselect_present.stat.exists
    - result_authselect_available_features.stdout is search("with-silent-lastlog")
  block:
    - name: Check integrity of authselect current profile
      ansible.builtin.command:
        cmd: authselect check
      register: result_authselect_check_cmd
      changed_when: false
      check_mode: false
      failed_when: false

    - name: Informative message based on the authselect integrity check result
      ansible.builtin.assert:
        that:
          - ansible_check_mode or result_authselect_check_cmd.rc == 0
        fail_msg:
          - authselect integrity check failed. Remediation aborted!
          - This remediation could not be applied because an authselect profile was not selected or the selected profile is not intact
          - It is not recommended to manually edit the PAM files when authselect tool is available
          - In cases where the default authselect profile does not cover a specific demand, a custom authselect profile is recommended.
        success_msg:
          - authselect integrity check passed

    - name: Get authselect Features Currently Enabled
      ansible.builtin.shell:
        cmd: authselect current | tail -n+3 | awk '{ print $2 }'
      register: result_authselect_features
      changed_when: false
      check_mode: false
      when:
        - result_authselect_check_cmd is success

    - name: Ensure "with-silent-lastlog" Feature is Disabled Using authselect Tool
      ansible.builtin.command:
        cmd: authselect disable-feature with-silent-lastlog
      register: result_authselect_disable_feature_cmd
      when:
        - result_authselect_check_cmd is success
        - result_authselect_features.stdout is search("with-silent-lastlog")

    - name: Ensure authselect changes are applied
      ansible.builtin.command:
        cmd: authselect apply-changes -b
      when: 
        - result_authselect_disable_feature_cmd is not skipped
        - result_authselect_disable_Feature_cmd is success
 
- name: Configure pam_lastlog.so in appropriate PAM files
  when: ("pam" in ansible_facts.packages and "kernel-core" in ansible_facts.packages)
  block:
    - name: Define the PAM file to be edited as a local fact
      ansible.builtin.set_fact:
        pam_file_path: /etc/pam.d/postlogin

    - name: Check if system relies on authselect tool:
      ansible.builtin.stat:
        path: /usr/bin/authselect
      register: result_authselect_present

    - name: Do the following if using authselect
      when: result_authselect_present.stat.exists
      block:
        - name: Check integrity of authselect current profile
          ansible.builtin.command:
            cmd: authselect check
          register: result_authselect_check_cmd
          changed_when: false
          check_mode: false
          failed_when: false

        - name: Informative message  based on authselect integrity check result
          ansible.builtin.assert:
            that:
              - result_authselect_check_cmd.rc == 0
            fail_msg:
              - authselect integrity check failed. Remediation aborted!
              - This remediation could not be applied because an authselect profile was not selected or the selected profile is not intact
              - It is not recommended to manually edit the PAM files when authselect tool is available
              - In cases where the default authselect profile does not cover a specific demand, a custom authselect profile is recommended.
            success_msg:
              - authselect integrity check passed

    - name: Ensure pam_lastlog.so is not configured with silent option
      
