---
- name: Ensure krb5 crypto-policies symlink is present
  ansible.builtin.file:
    src: /etc/crypto-policies/back-ends/krb5.config
    dest: /etc/krb5.conf.d/crypto-policies
    state: link
    force: true
