---
- name: Security and Customization Workflow
  hosts: localhost
  gather_facts: false
  become: true
  become_method: sudo
  tasks:
    - name: Include Security Role
      ansible.builtin.include_role:
        name: ../roles/security-baseline
      tags:
        - SEC

    - name: Include Quality of Life
      ansible.builtin.include_role:
        name: ../roles/quality_of_life
      tags:
        - QOF
